import * as THREE from "https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js";
const canvas=document.querySelector("#game"),renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x080a0f);scene.fog=new THREE.Fog(0x080a0f,10,38);const camera=new THREE.PerspectiveCamera(70,2,.1,100);camera.position.set(0,1.7,7);
const mat=(c,r=.7,m=.05)=>new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:m});function box(x,y,z,w,h,d,c,r=.7,m=.05){let o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(c,r,m));o.position.set(x,y,z);o.castShadow=o.receiveShadow=true;scene.add(o);return o}
box(0,-.1,0,24,.2,30,0x161317);box(0,4.5,0,24,.2,30,0x0c0d11);box(-12,2,0,.2,5,30,0x17131a);box(12,2,0,.2,5,30,0x17131a);box(0,2,-15,24,5,.2,0x17131a);for(let x=-10;x<=10;x+=2)box(x,.02,0,.025,.025,30,0x9b713b,.4,.2);
box(0,1,-8,10,1.2,1.1,0x321c15,.45,.1);box(0,2.45,-8.5,10,1.8,.3,0x1a1110);for(let x=-4;x<=4;x+=2){box(x,1.65,-7.85,.08,.75,.08,0xe3b15d,.25,.5);box(x,2.05,-7.85,.32,.55,.32,[0x6b1d19,0x184e3d,0x795c22][(x+4)/2%3],.3,.1)}for(let x=-4;x<=4;x+=2){box(x,.55,-6.4,.8,.15,.8,0x3a2520);box(x,.25,-6.4,.12,.6,.12,0x222228,.3,.5)}
for(const [x,z] of [[-7,1],[-7,-4],[7,1],[7,-4]]){box(x,.75,z,2.8,.12,1.6,0x3a241b);box(x,.38,z,.15,.75,.15,0x222228,.3,.5);for(let dz of [-1.2,1.2])box(x,.45,z+dz,1.2,.8,.65,0x4a2020)}box(0,.03,9,8,.03,5,0x401b22);
for(let x=-9;x<=9;x+=3){let l=new THREE.PointLight(x%2?0xff6d32:0xe8aa55,18,7,2);l.position.set(x,3.5,-6);scene.add(l)}let neon=new THREE.PointLight(0x8b45ff,25,10,2);neon.position.set(0,2.8,5);scene.add(neon);scene.add(new THREE.HemisphereLight(0x5d6688,0x24150f,1.5));
const sign=document.createElement("canvas");sign.width=1024;sign.height=256;let c=sign.getContext("2d");c.fillStyle="#111118";c.fillRect(0,0,1024,256);c.font="bold 90px Arial";c.textAlign="center";c.fillStyle="#f2b54b";c.shadowBlur=30;c.shadowColor="#f2b54b";c.fillText("SOCIAL LOUNGE",512,145);let tex=new THREE.CanvasTexture(sign),sp=new THREE.Mesh(new THREE.PlaneGeometry(7,1.75),new THREE.MeshBasicMaterial({map:tex}));sp.position.set(0,2.7,-8.3);scene.add(sp);
let coins=Number(localStorage.getItem("slcoins")||50),coinEl=document.querySelector("#coins");coinEl.textContent=coins;const keys={},start=document.querySelector("#start"),intro=document.querySelector("#intro"),menu=document.querySelector("#menu"),prompt=document.querySelector("#prompt"),cross=document.querySelector("#crosshair");let active=false,yaw=0,pitch=0,last=performance.now(),earn=0;
start.onclick=()=>{intro.classList.add("hidden");canvas.requestPointerLock()};document.addEventListener("pointerlockchange",()=>{active=document.pointerLockElement===canvas;cross.style.display=active?"block":"none"});document.addEventListener("mousemove",e=>{if(!active)return;yaw-=e.movementX*.0022;pitch=Math.max(-1.3,Math.min(1.3,pitch-e.movementY*.0022))});
addEventListener("keydown",e=>{keys[e.code]=true;if(e.code==="KeyE"&&active&&camera.position.z<-5.2){document.exitPointerLock();menu.classList.remove("hidden")}});addEventListener("keyup",e=>keys[e.code]=false);document.querySelector("#close").onclick=()=>{menu.classList.add("hidden");canvas.requestPointerLock()};document.querySelectorAll("[data-buy]").forEach(b=>b.onclick=()=>{let p=+b.dataset.buy;if(coins>=p){coins-=p;save();toast(`🍹 ${b.dataset.item} bestellt – ${p} Coins`)}else toast("Nicht genug Lounge Coins.")});
function save(){coinEl.textContent=coins;localStorage.setItem("slcoins",coins)}function toast(t){let e=document.querySelector("#toast");e.textContent=t;e.style.opacity=1;setTimeout(()=>e.style.opacity=0,2200)}function resize(){let w=innerWidth,h=innerHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}addEventListener("resize",resize);resize();
function loop(now){requestAnimationFrame(loop);let dt=Math.min((now-last)/1000,.05);last=now;camera.rotation.order="YXZ";camera.rotation.y=yaw;camera.rotation.x=pitch;if(active){let f=new THREE.Vector3(Math.sin(yaw),0,-Math.cos(yaw)),r=new THREE.Vector3(Math.cos(yaw),0,Math.sin(yaw)),v=new THREE.Vector3();if(keys.KeyW)v.add(f);if(keys.KeyS)v.sub(f);if(keys.KeyD)v.add(r);if(keys.KeyA)v.sub(r);if(v.length())v.normalize().multiplyScalar(3.2*dt);camera.position.add(v);camera.position.x=Math.max(-10.8,Math.min(10.8,camera.position.x));camera.position.z=Math.max(-13.5,Math.min(13.5,camera.position.z));earn+=dt;if(earn>=60){earn-=60;coins+=5;save();toast("✨ +5 Lounge Coins für aktive Lounge-Zeit!")}let near=camera.position.z<-5.2;prompt.style.display=near?"block":"none";prompt.textContent="E  •  BAR-MENÜ ÖFFNEN"}renderer.render(scene,camera)}requestAnimationFrame(loop);